name: Deploy React App

on:
  push:
    branches:
      - develop  # Staging environment
      - main     # Production environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: |
          npm install || echo "Error: npm install failed, skipping..."
      
      - name: Build React App
        run: |
          npm run build || echo "Error: Build failed, skipping..."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: |
          npm test || echo "Error: Tests failed, skipping..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Determine Deployment Environment
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "DEPLOY_PATH=/var/www/staging/portal" >> $GITHUB_ENV
          else
            echo "DEPLOY_PATH=/var/www/production/portal" >> $GITHUB_ENV
          fi

      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }} || echo "Error: Deployment path not found, skipping..."
            git pull origin ${{ github.ref_name }} || echo "Error: git pull failed, skipping..."
            npm install || echo "Error: npm install failed, skipping..."
            npm run build || echo "Error: Build failed, skipping..."
            sudo systemctl restart nginx || echo "Error: Nginx restart failed, skipping..."
