name: Deploy Frontend Dabdoobkids (portal react app)

on:
  push:
    branches:
      - develop  # Staging environment
      - main     # Production environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps || echo "Error: npm install failed, skipping..."
      
      - name: Build React App
        run: |
          npm run build || echo "Error: Build failed, skipping..."

  test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Tests
        run: |
          npm test || echo "Error: Tests failed, skipping..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Determine Deployment Environment
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "DEPLOY_PATH=/var/www/staging/portal" >> $GITHUB_ENV
          else
            echo "DEPLOY_PATH=/var/www/production/portal" >> $GITHUB_ENV
          fi

      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: "82.29.170.114"
          username: "root"
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/github_key  # Ensure the correct key is used
            cd ${{ env.DEPLOY_PATH }} || { echo "Error: Deployment path not found"; exit 1; }
            echo "Fetching latest code..."
            git pull origin ${{ github.ref_name }} || { echo "Error: git pull failed. Stopping deployment!"; exit 1; }
            npm install --legacy-peer-deps || { echo "Error: npm install failed"; exit 1; }
            npm run build || { echo "Error: Build failed"; exit 1; }
            sudo systemctl restart nginx || { echo "Error: Nginx restart failed."; exit 1; }
